_wandb:
    value:
        cli_version: 0.22.2
        e:
            vofksy7r3y3i05qusei7126g9zhcxk77:
                codePath: eval.py
                codePathLocal: eval.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "510973177856"
                        used: "367731564544"
                email: rahul.tfx@gmail.com
                executable: C:\Users\rjdis\AppData\Local\Programs\Python\Python311\python.exe
                git:
                    commit: 820045732ad16f7948c932155e7a3cabd3dbe2f2
                    remote: https://github.com/leonado10000/research.git
                gpu: NVIDIA GeForce RTX 3050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2048
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce RTX 3050 Laptop GPU
                      uuid: GPU-e4297789-6045-185a-e6be-c6d570820172
                host: Leo
                memory:
                    total: "16473034752"
                os: Windows-10-10.0.26100-SP0
                program: c:\Users\rjdis\OneDrive\Documents\GitHub\research\eval.py
                python: CPython 3.11.2
                root: C:\Users\rjdis\OneDrive\Documents\GitHub\research
                startedAt: "2025-11-07T17:13:58.176294Z"
                writerId: vofksy7r3y3i05qusei7126g9zhcxk77
        m: []
        python_version: 3.11.2
        t:
            "1":
                - 1
                - 41
                - 105
            "2":
                - 1
                - 41
                - 105
            "3":
                - 16
            "4": 3.11.2
            "5": 0.22.2
            "8":
                - 2
                - 3
            "12": 0.22.2
            "13": windows-amd64
dataset:
    value: MNIST
device:
    value: cuda
epochs:
    value: 10
framework:
    value: pytorch
model:
    value: cnn_pytorch
